server:
  port: ${port:8080}

# 静态资源路径配置,自定义配置
wyait:
  picpath : F:\cache\java\douyu


spring:
    kaptcha:
        enable: true
        properties:
          kaptcha.border: no
          kaptcha.border.color: 105,179,90
          kaptcha.textproducer.font.color: blue
          kaptcha.image.width: "125"
          kaptcha.image.height: "45"
          kaptcha.textproducer.font.size: "45"
          kaptcha.session.key: KAPTCHA_SESSION_KEY
          kaptcha.textproducer.char.length: "4"
          kaptcha.textproducer.font.names: 宋体,楷体,微软雅黑
        suffix: suffix


roomId : 67373
spring:
  resources:
    static-locations: /META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${wyait.picpath}
  thymeleaf:
    mode: HTML5
    encoding: utf-8
   # prefix: classpath:/templates
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://172.18.28.183:3366/douyu?characterEncoding=utf-8&characterSetResults=utf-8&useUnicode=true&useSSL=false
#    username: root
#    password: 123456...
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  mvc:
#  表示所有的访问都经过静态资源路径
    static-path-pattern: /**