server:
  port: ${port:8080}

# 静态资源路径配置,自定义配置
wyait:
  picpath : F:\cache\java\douyu



msg: 哈哈哈哈哈哈，老子天下第一
roomId : 67373
spring:
  resources:
    static-locations: /META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${wyait.picpath}
  thymeleaf:
    mode: HTML5
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.18.28.183:3306/douyu?characterEncoding=utf-8&characterSetResults=utf-8&useUnicode=true&useSSL=false
    username: root
    password: 123456...
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  mvc:
#  表示所有的访问都经过静态资源路径
    static-path-pattern: /**